#!/bin/bash
# description: Slapd Start Stop Restart
# processname: slapd
# chkconfig: 234 20 80

LD_LIBRARY_PATH="/usr/share/db-6.2.32/build_unix/.libs"
export LD_LIBRARY_PATH

case $1 in
start)
echo "starting slapd server"
/usr/local/libexec/slapd -F /usr/local/etc/openldap/slapd.d
;;
stop)
echo "stopping slapd server"
if [ -f "cat /usr/local/var/run/slapd.pid" ]
then
	kill -INT `cat /usr/local/var/run/slapd.pid`
else
	kill -9 `pidof slapd`
fi
;;
restart)
echo "stopping slapd server"
if [ -f "cat /usr/local/var/run/slapd.pid" ]
then
	kill -INT `cat /usr/local/var/run/slapd.pid`
else
	kill -9 `pidof slapd`
fi
echo "starting slapd server"
/usr/local/libexec/slapd -F /usr/local/etc/openldap/slapd.d
;;
esac
exit 0